# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build fail2ban-dashboard

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .golangci.yml
  push:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .golangci.yml

permissions:
  contents: read

env:
  CGO_ENABLED: 0

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Display Go version
        run: go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0

      - name: Build
        run: |
          make build
